# Extends the default yamllint config by adjusting some options.
extends: default

rules:
  braces: { min-spaces-inside: 0, max-spaces-inside: 2 }
  comments-indentation: disable
  line-length:
    level: warning
    allow-non-breakable-inline-mappings: true
  truthy: disable
